version = 1
SPDX-PackageName = "OATHDO"
SPDX-PackageSupplier = "Eimy Herrer"
SPDX-PackageDownloadLocation = "https://github.com/eimyroot/OATHDO"

[[annotations]]
path = ["*", "**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Eimy Herrer"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["LICENSE", "LICENSES/Apache-2.0.txt"]
precedence = "override"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "Apache-2.0"
